# Generated by Django 4.2.7 on 2023-11-16 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('KBL', 'کابل'), ('Badakhshan', 'بدخشان'), ('Baghlan', 'بغلان'), ('Kondoz', 'کندوز'), ('Takhar', 'تخار'), ('Balkh', 'بلخ'), ('Faryab', 'فاریاب'), ('Jawzjan', 'جوزجان'), ('Samangan', 'سمنگان'), ('Sar-e-pol', 'سر پل'), ('Bamyan', 'بامیان'), ('Kapisa', 'کاپیسا'), ('Logar', 'لوگر'), ('Panjsher', 'پنجشیر'), ('Parwan', 'پروان'), ('Maidan-wardak', 'میدان وردګ'), ('Konar', 'کنړ'), ('Laghman', 'لغمان'), ('Noristan', 'نوریستان'), ('Badghis', 'بادغیس'), ('Farah', 'فراه'), ('Ghor', 'غور'), ('Herat', 'هرات'), ('Ghazni', 'غزنی'), ('Khost', 'خوست'), ('Paktia', 'پکتیا'), ('Paktika', 'پکتیکا'), ('Daykondi', 'دایکندی'), ('Helmand', 'هلمند'), ('Kandahar', 'کندهار'), ('Nimroz', 'نیمروز'), ('Orozgan', 'اورزګان'), ('Zabul', 'زابل')], max_length=255, verbose_name='ولایت')),
                ('woleswali', models.CharField(default='کابل', max_length=255, verbose_name='ولسوالی')),
                ('district', models.CharField(choices=[('1', 'ناحیه اول'), ('2', 'ناحیه دوم'), ('3', 'ناحیه سوم'), ('4', 'ناحیه چهارم'), ('5', 'ناحیه پنجم'), ('6', 'ناحیه ششم'), ('7', 'ناحیه هفتم'), ('8', 'ناحیه هشتم'), ('9', 'ناحیه نهم'), ('10', 'ناحیه دهم'), ('11', 'ناحیه یازدهم'), ('12', 'ناحیه دوازدهم'), ('13', 'ناحیه سیزدهم'), ('14', 'ناحیه چهاردهم'), ('15', 'ناحیه پانزدهم'), ('16', 'ناحیه شانزدهم'), ('17', 'ناحیه هفدهم'), ('18', 'ناحیه هجدهم'), ('19', 'ناحیه نوزدهم'), ('20', 'ناحیه بیستم'), ('21', 'ناحیه بیست ویکم')], max_length=255, verbose_name='ناحیه')),
                ('road', models.CharField(default='ندارد', max_length=255, verbose_name='سرک')),
                ('avenue', models.CharField(default='ندارد', max_length=255, verbose_name='کوچه')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
        migrations.CreateModel(
            name='Educational_Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='نوت')),
            ],
            options={
                'verbose_name': 'نوع مدرک تحصیلی',
                'verbose_name_plural': 'انواع مدارک تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='License_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نوعیت جواز')),
                ('remarks', models.CharField(blank=True, default='ندارد', max_length=255, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'نوع جواز',
                'verbose_name_plural': 'انواع جوازات',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('owner_name', models.CharField(max_length=255, verbose_name='نام صاحب امتیاز')),
                ('owner_father_name', models.CharField(max_length=255, verbose_name='ولد صاحب امتیاز')),
                ('owner_grand_father_name', models.CharField(max_length=255, verbose_name='ولدیت صاحب امتیاز')),
                ('owner_tazkira_number', models.CharField(max_length=255, verbose_name='تذکره نمبر صاحب امتیاز')),
                ('address', models.CharField(default='null', max_length=255, verbose_name='آدرس محل')),
                ('contact', models.CharField(blank=True, help_text='0784009003', max_length=10, null=True, verbose_name='شماره تماس')),
                ('remarks', models.TextField(default='null', max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='زمان تغییر')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_plans_payment_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شد')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_plans_payment_updated', to=settings.AUTH_USER_MODEL, verbose_name='تغییر شد')),
            ],
            options={
                'verbose_name': 'نهاد صحی',
                'verbose_name_plural': 'تاسیسات صحی',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم')),
                ('last_name', models.CharField(max_length=255, verbose_name='تخلص')),
                ('father_name', models.CharField(max_length=255, verbose_name='ولد')),
                ('grand_father_name', models.CharField(blank=True, default='خالی', max_length=255, null=True, verbose_name='ولدیت')),
                ('gender', models.CharField(choices=[('Male', 'مرد'), ('Female', 'زن'), ('Other', 'دیگر')], max_length=10, verbose_name='جنسیت')),
                ('nationaliy', models.CharField(choices=[('Afghan', 'افغان'), ('Khariji', 'خارجی')], max_length=10, verbose_name='ملیت')),
                ('id_no', models.CharField(max_length=20, unique=True, verbose_name='تذکره / پاسپورت نمبر')),
                ('primary_phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('secondary_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس دوم')),
                ('license_number', models.CharField(max_length=20, unique=True, verbose_name='شماره جواز')),
                ('license_issue_date', models.DateField()),
                ('license_expiry_date', models.DateField()),
                ('status', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes', verbose_name='کیو ار کد')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='services/customer/images', verbose_name='عکس')),
                ('remarks', models.TextField(blank=True, default='ملاحظه ای ندارد!', null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='زمان تغییر')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شد')),
                ('current_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers_current', to='mis.address', verbose_name='آدرس')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.educational_degree', verbose_name='سطح تحصیلی')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.license_type', verbose_name='نوعیت جواز')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.organization', verbose_name='نهاد صحی')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_updated', to=settings.AUTH_USER_MODEL, verbose_name='تغییر شد')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': ' مشتری ها',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان')),
                ('document', models.FileField(upload_to='attachment/files')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان اپلود شد')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mis.employee', verbose_name='سند')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شد')),
            ],
            options={
                'verbose_name': 'عکس محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
