# Generated by Django 5.0.6 on 2024-06-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'فایل ضمیمه', 'verbose_name_plural': 'ضمیمه ها'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'کدر صحی', 'verbose_name_plural': ' کدر ها'},
        ),
    ]
