# Generated by Django 4.2.7 on 2023-11-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='woleswali',
            field=models.CharField(default='کابل', max_length=255, verbose_name='ولسوالی'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(choices=[('1', 'ناحیه اول'), ('2', 'ناحیه دوم'), ('3', 'ناحیه سوم'), ('4', 'ناحیه چهارم'), ('5', 'ناحیه پنجم'), ('6', 'ناحیه ششم'), ('7', 'ناحیه هفتم'), ('8', 'ناحیه هشتم'), ('9', 'ناحیه نهم'), ('10', 'ناحیه دهم'), ('11', 'ناحیه یازدهم'), ('12', 'ناحیه دوازدهم'), ('13', 'ناحیه سیزدهم'), ('14', 'ناحیه چهاردهم'), ('15', 'ناحیه پانزدهم'), ('16', 'ناحیه شانزدهم'), ('17', 'ناحیه هفدهم'), ('18', 'ناحیه هجدهم'), ('19', 'ناحیه نوزدهم'), ('20', 'ناحیه بیستم'), ('21', 'ناحیه بیست ویکم')], max_length=255, verbose_name='ناحیه'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(choices=[('KBL', 'کابل'), ('Badakhshan', 'بدخشان'), ('Baghlan', 'بغلان'), ('Kondoz', 'کندوز'), ('Takhar', 'تخار'), ('Balkh', 'بلخ'), ('Faryab', 'فاریاب'), ('Jawzjan', 'جوزجان'), ('Samangan', 'سمنگان'), ('Sar-e-pol', 'سر پل'), ('Bamyan', 'بامیان'), ('Kapisa', 'کاپیسا'), ('Logar', 'لوگر'), ('Panjsher', 'پنجشیر'), ('Parwan', 'پروان'), ('Maidan-wardak', 'میدان وردګ'), ('Konar', 'کنړ'), ('Laghman', 'لغمان'), ('Noristan', 'نوریستان'), ('Badghis', 'بادغیس'), ('Farah', 'فراه'), ('Ghor', 'غور'), ('Herat', 'هرات'), ('Ghazni', 'غزنی'), ('Khost', 'خوست'), ('Paktia', 'پکتیا'), ('Paktika', 'پکتیکا'), ('Daykondi', 'دایکندی'), ('Helmand', 'هلمند'), ('Kandahar', 'کندهار'), ('Nimroz', 'نیمروز'), ('Orozgan', 'اورزګان'), ('Zabul', 'زابل')], max_length=255, verbose_name='ولایت'),
        ),
    ]
