# Generated by Django 4.2.7 on 2023-11-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0003_address_woleswali_alter_address_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('owner_name', models.CharField(max_length=255, verbose_name='نام صاحب امتیاز')),
                ('owner_father_name', models.CharField(max_length=255, verbose_name='ولد صاحب امتیاز')),
                ('owner_grand_father_name', models.CharField(max_length=255, verbose_name='ولدیت صاحب امتیاز')),
                ('owner_tazkira_number', models.CharField(max_length=255, verbose_name='ولدیت صاحب امتیاز')),
                ('address', models.CharField(default='null', max_length=255, verbose_name='آدرس محل')),
                ('contact', models.CharField(blank=True, help_text='0784009003', max_length=10, null=True, verbose_name='شماره تماس')),
                ('remarks', models.TextField(max_length=255, verbose_name='نام صاحب امتیاز')),
            ],
            options={
                'verbose_name': 'تاسیس صحی',
                'verbose_name_plural': 'تاسیسات صحی',
            },
        ),
    ]
