# Generated by Django 5.0.6 on 2024-06-07 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0003_educationalfield_fees_educationdetails_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Educational_Degree',
            new_name='EducationalDegree',
        ),
        migrations.RenameModel(
            old_name='License_Type',
            new_name='LicenseType',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'کدر صحی', 'verbose_name_plural': 'کدر ها'},
        ),
        migrations.RenameField(
            model_name='educationdetails',
            old_name='institude',
            new_name='institute',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='nationaliy',
            new_name='nationality',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mis.employee', verbose_name='سند'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='current_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='mis.address', verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='license_expiry_date',
            field=models.DateField(verbose_name='تاریخ انقضای جواز'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='license_issue_date',
            field=models.DateField(verbose_name='تاریخ صدور جواز'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شد'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_updated', to=settings.AUTH_USER_MODEL, verbose_name='تغییر شد'),
        ),
    ]
