# Generated by Django 4.2.7 on 2023-11-16 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mis', '0004_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_plans_payment_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شد'),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='زمان تغییر'),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_plans_payment_updated', to=settings.AUTH_USER_MODEL, verbose_name='تغییر شد'),
        ),
    ]
