# Generated by Django 5.0.6 on 2024-06-07 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0004_rename_educational_degree_educationaldegree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fees',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mis.fees', verbose_name='تعیین شوۍ فیس'),
            preserve_default=False,
        ),
    ]
